# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Session-Serialize-yaml
version:      1.0
version_from: lib/CGI/Session/Serialize/yaml.pm
installdirs:  site
requires:
    CGI::Session:                  4
    YAML:                          0.50

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
